# fly.toml app configuration file generated for password-generator-fmpwzg on 2024-11-28T22:46:04Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'password-generator-fmpwzg'
primary_region = 'mia'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
